export type WindowMeasurement = {
  id: string;
  number: number;
  name: string;
  measuredDate: string;
  internalWidth: number;
  internalHeightL: number;
  internalHeightR: number;
  reveal: number;
  revealOther: string | null;
  blindAbove?: number;
  blindLeft?: number;
  blindRight?: number;
  blindUnderhang?: number;
  blindFixingType: string;
  blindFixingTypeOther: string;
  controlSide: string;
  controlLength: string;
  controlLengthOther: string;
  blindWidthError: string;
  blindCount: number | string;
  blindLeftWidth: string;
  fixing: string;
  fixingOther: string;
  sunProtection: string;
  sunProtectionOther: string;
  notes: string;
  photos: string[] | null;
  outsideBlindFixingType: string;
  outsideBlindFixingTypeOther: string;
  outsideBlindCount: number;
  outsideBlindLeftWidth: string;
  squareDiff: number;

  // curtainFabric: string | null;
  // treatment: string[] | null;
  // blindExtras: string[] | null;
  // blindPrice: string | null;
  // curtainType: string | null;
  // drawType: string;
  // outsideBlind2Type: string;
  // outsideBlind2Fabric: string;
  // outsideControlSide: string;
  // outsideBlindType: string;
  // outsideBlindFabric: string;
  // outsideBlindExtras: string[] | null;
  // fabricSearch: string;
  // amountOnFloor: string;
  // existingTrackType: string;
  // existingTrackTypeOther: string;
  // newTrackType: string;
  // newTrackTypeOther: string;
  // pelmetType: string;
  // bracketColour: string;
  // bottomRailType: string;
  // bottomRailColour: string;
  // chainColour: string;
  // headrailColour: string;
  // sideChannels: boolean;
  // shutterColourSurcharge: number;
  // shutterTrack: string;
  // fauxwoodFascia: boolean;
  // extraRemotes: number;
  // extraCables: number;
  // extraHubs: number;
  // curtainConfig: string;
  // pleatingStyle: string;
  // cordControlSide: string;
  // rollerRoll: string;
  // blindType: string;
  // blindFabric: string;
  // blind2Type: string;
  // blind2Fabric: string;
};
